version: "3.8"
services:
  metrics-service-1:
    container_name: metrics-service-1
    build:
      context: ./metrics-service-1
      dockerfile: service1.Dockerfile
    ports:
      - "8000:8000"
    restart: always

  metrics-service-2:
    container_name: metrics-service-2
    build:
      context: ./metrics-service-2
      dockerfile: service2.Dockerfile
    ports:
      - "8010:8000"
    restart: always

  generator:
    container_name: generator
    build:
      context: ./generator
      dockerfile: generator.Dockerfile
    restart: always
    depends_on:
      - metrics-service-1
      - metrics-service-2

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always
    depends_on:
      - metrics-service-1
      - metrics-service-2

  grafana:
    container_name: grafana
    image: grafana/grafana:8.5.3
    volumes:
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/default.yml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/default.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - prometheus