global:
  scrape_interval: 3s

scrape_configs:
  - job_name: "script-metrics"
    metrics_path: /metrics
    static_configs:
      - targets:
          - metrics-service-1:8000
          - metrics-service-2:8000