{
 "title": "Example dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "General Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "requests_total" }
   ]
  },
  {
   "title": "All Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(requests_total)" }
   ]
  },
  {
   "title": "All Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(requests_total{status_code=~\"4..|5..\"})"
    }
   ]
  },
  {
   "title": "RPS All",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(rate(requests_total[15s]))" }
   ]
  },
  {
   "title": "Errors percentage of all requests per 15 sec",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(requests_total{status_code=~\"4..|5..\"}[15s]))/sum(rate(requests_total[15s])) * 100"
    }
   ]
  },
  {
   "title": "Error PS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(requests_total{status_code=~\"4..|5..\"}[15s])"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(requests_total[15s]))"
    }
   ]
  },
  {
   "title": "Errors percentage of all requests by instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(requests_total{status_code=~\"4..|5..\"}[15s])) by(instance) /sum(rate(requests_total[15s])) by(instance) * 100"
    }
   ]
  },
  {
   "title": "Errors by instances",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "requests_total{status_code=~\"4..|5..\"}"
    }
   ]
  }
 ]
}